### ISSUE TITLE
local variable 'table_type' referenced before assigment

### ISSUE THREAD

**Issue by dom1202** [DonyorM/weresync#12] opened 2017-12-16 21:50 UTC
Hello,
I am just trying to use weresync-gui to clone a running drive (and weresync) because it looks to me very interesting like Carbon Copy Cloner on mac. .
I am under ubuntu 17.10 on disk sde, 
I have installed Ubuntu 17.04 on sdc  (thinking it would help cloning).
Running weresync-gui with: source: /dev/sde to destination:  /dev/sdc 
- with Bootloader UUID Copy checked  ,and root partition 2 :
But I got the following error :
Error starting clone : local variable 'table_type' referenced before assigment.
Idem if I run from terminal with : sudo weresync -C /dev/sde /dev/sdc
I am far for being an expert . So
Please can someone tell me what this means and ... may be the 'solution'.
Dominique

**Comment by DonyorM** [comment] 2017-12-18 04:09
Could you give me a gist or a pastebin of the log file, located at `/var/log/weresync`?

**Comment by dom1202** [comment] 2017-12-18 15:10
Hello,
Thanks for reacting so fast
Here in weresync-copie.doc joined what I got from weresync.log.
For your information my computer has
- sda hackintosh OSX Snow leopard
- sdb hackintosh OSX Snow leopard
- sdc : Ubuntu 17.04
- sdc Ubuntu not working
- sde Ubuntu 17.10

If running from terminal : sudo weresync -C /dev/sde /dev/sdc
[sudo] Mot de passe de dvmbp :
Traceback (most recent call last):
File "/usr/sbin/weresync", line 11, in <module>
load_entry_point('WereSync==1.0.7', 'console_scripts', 'weresync')()
File "/usr/share/weresync/weresync/interface.py", line 514, in main
bootloader=args.bootloader,)
File "/usr/share/weresync/weresync/interface.py", line 287, in copy_drive
target_manager.get_partition_table_type()
File "/usr/share/weresync/weresync/device.py", line 256, in get_partition_table_type
if table_type not in SUPPORTED_PARTITION_TABLE_TYPES:
UnboundLocalError: local variable 'table_type' referenced before assignment


Thanks again  for help 
Dominque

**Comment by DonyorM** [comment] 2017-12-18 15:27
Hmmmm, what is the output of `parted -s /dev/sde print`?

**Comment by dom1202** [comment] 2017-12-18 15:50
here:
Modèle: ATA ST2000DM001-1ER1 (scsi)
Disque /dev/sde : 2000GB
Taille des secteurs (logiques/physiques): 512B/4096B
Table de partitions : msdos
Disk Flags:
Numéro Début Fin Taille Type Système de fichiers Fanions
1 1049kB 50,3MB 49,3MB primary linux-swap(v1)
2 50,3MB 50,1GB 50,0GB primary ext4 démarrage
3 50,1GB 900GB 850GB primary ext4

Thanks!
D.

**Comment by DonyorM** [comment] 2017-12-18 16:12
Right. As of now this issue is caused by the `parted` command outputting in French. I'll try and get out an update that fixes that as soon as possible. For now, I imagine temporarily changing your locale to English (en_US.UTF-8) should work, but I'm not 100% sure. I'll test and fix it tomorrow.

**Comment by dom1202** [comment] 2017-12-18 16:28
I changed in english  : [Anglais (US) en], but  I don't know if it is [en_US.UTF-8] I guess it is correct.
however I got the same error.......???
See you later with pleasure.
Anyway congratulations for this soft. I know this is not easy (I have done the same for mac and I still have some problem with booting...)
Dominique

**Comment by dom1202** [comment] 2018-01-18 17:08
Hello sir,

First of all : All my best wishes for 2018 !!!.

You remember probably my question about weresync and the mails between you and me about the issue «  local variable 'table_type' referenced before assigment ».

I have been away from home and being back I tried again wersesync but still the same problem.

Meanwhile have you found an explanation and hopefully a solution. You were wrinting : « this issue is caused by the parted command outputting in French ».

Thanks again. I hope this soft will be working because I think this one is a wonderfull solution.

I will be happy to hear from you

dominique

**Comment by DonyorM** [comment] 2018-03-31 14:29
This should be fixed in v1.0.8. Please run `pip3 install --upgrade weresync` to download the latest version from PyPI and install it. 

I'm going to close the issue for now, but feel free to re-open it if this doesn't solve the problem.

**Closed by DonyorM** 2018-03-31 14:29 UTC
